hivtools/hint-deploy

README.md, config/hint.yml, src/hint_deploy.py
This PR will add a basic nginx proxy to the constellation. Currently this uses only a self-signed certificate, hopefully @weshinsley can organise us a real cert and later we can update it with the proper hostname (mrc-666).
(We need a real cert up so that we can get ICT to open ports, etc).
=> mrc-665: add a proxy to the constellation

.travis.yml, config/production.yml, config/staging.yml, requirements.txt, src/hint_cli.py, src/hint_deploy.py, test/test_cli.py, test/test_integration.py
This PR will add the certificates to the proxy container, using the vault.  The vault process is described in https://github.com/reside-ic/proxy-nginx/pull/3
This also allows for a level of sub-configuration - here staging and production following much the same pattern as orderly-web-deploy, though the configuration is not persisted into the container at present.
Should ideally be merged after https://github.com/reside-ic/constellation/pull/3, with the .travis.yml updated to not point at the branch and install from pypi.
The staging instance is currently handled in https://github.com/mrc-ide/hint-deploy/pull/3 and these PRs interact but can be merged in any order
=> mrc-677: add ssl certs to the deployment

README.md, scripts/slow
This PR will add support for using [toxiproxy](https://toxiproxy.io) to simulate slower connections, for use in testing.
I've not added this as an explicit container to the constellation, but we could do that later if it feels more natural - the bulk of the `start` function would become a configure function.  The blocking issue on doing this is creating support for different configurations for production and testing, really.  This way also makes it easy to use the slow proxy outside of a full deployment, e.g., in development of hint itself.  It will affect whatever is running on port 8080 on the host.
=> mrc-655: support for running with simulated slow connections

config/hint.yml, config/production.yml, src/hint_deploy.py, test/test_config.py
This PR uses a shared volume for configuration - mounted read-write into `hint` and read-only into the cli tool. The configuration is expanded to include enough to send an email, and the configuration has been updated for production to enable this (we might also want this on staging?)
=> MRC-701: Use a shared volume for configuration

.travis.yml, config/hint.yml, config/production.yml, requirements.txt, src/hint_deploy.py, test/test_integration.py
This PR adds support for a scalable number of workers and updates the configurations accordingly. No workers are created in the hintr container, which runs now just a single process.
This PR replaces #7, which is failing on travis for unknown reasons.
Originally a squash commit, originally composed of:
* 9d1b81a Remove fetching source from github
* ed6705c Fix typo in test
* 0508b14 Try to fix travis
* 918c199 Add test of final worker state
* 3d58fb7 Additional tests
* 0a4485d Support for scalable workers
=> MRC-685: Flexible number of workers

config/staging.yml, test/test_config.py
Coupled with https://github.com/mrc-ide/hint/pull/157 should allow us to start sending emails. Tbf we could test from prod, sending to our own email addresses, but might be nice to have it work on staging for testing.
=> let staging send emails also

src/hint_deploy.py, test/test_config.py, test/test_integration.py
This PR sets the hint application url to be that of the proxy (the externally facing URL), scrubbing the port number where a standard https port is used.  I've tested this locally with the staging configuration and I get a sensible email back out
=> mrc-728: fix application url

src/hint_deploy.py, test/test_integration.py
Now the cli can send emails if no password is provided, don't prompt for one.
=> mrc-710: Don't prompt for password

config/hint.yml, src/hint_deploy.py
This enables the key persistence in https://github.com/mrc-ide/hint/pull/165
=> mrc-730: create key directory before hint startup

config/production.yml, src/hint_cli.py, src/hint_deploy.py, test/test_cli.py, test/test_integration.py
This PR will protect against unwanted data loss when using the deploy tool, as discussed in the kitchen on Wednesday
The only real way we lose data is if the volumes are removed.  That happens with `./hint stop --volumes` and `hint --destroy`, which is basically just a wrapper around `./hint stop --volumes --networks --kill`.
When we're running in most environments, including testing situations, we will prompt the user and explain what the consequences are.
When we're running in production we should not lose data ever, so it is just flat out refused. Rather than switch on the configuration name, this is based off of the configuration option `deploy: protect_data: <bool>`, which is enabled in production.yml
=> mrc-742: Protect from data loss

.travis.yml, README.md, requirements.txt, src/hint_cli.py, src/hint_deploy.py, test/test_cli.py, test/test_integration.py
This PR will allow fairly graceful upgrades of hintr, or of all containers.
For hintr upgrade we
1. pull a new hintr image
2. tell workers to stop once they've finished any jobs
3. stop the hintr server
4. bring up the new hintr server
5. bring up new workers
This will leave current sessions unaffected, and current running jobs will continue.  There will be a period of hintr outage, hopefully < 3 s
For the full upgrade we are less graceful and simply
1. pull all images
2. stop all containers (gracefully, slower than kill)
3. start the whole thing again
This will close all client connections and require re-login.
I am not sure if we should call this "upgrade" or "update". Thoughts?
This PR depends on #14 and https://github.com/reside-ic/constellation/pull/5 and the `.travis.yml` should be …
=> mrc-697: upgrade hintr and the whole app

src/hint_cli.py, src/hint_deploy.py, test/test_integration.py
This PR will skip adding users that already exist. This is needed to start a hint constellation with a test user for a second time.
=> mrc-783: don't error if adding users that already exist

README.md, config/production.yml
This PR updates the configuration to use the unaids address rather than our in-house address for production.
Instructions added, based on what I just did
=> MRC-789: Use unaids domain

src/hint_cli.py, test/test_config.py, test/test_integration.py
Previously if containers went down and the system was started up again with `./hint-deploy start` the configuration name was lost. This PR repairs that.  The modifications to the integration test replicate the previous scenario that lead to the loss of the configuration name.
=> mrc-799: don't lose container configuration name after container loss

README.md
This PR adds deploy instructions. ~It should not be merged until after #19 because the deploy on staging is broken until that is fixed (although mrc-783 is currently checked out on staging so it's not too bad)~
=> mrc-727: Add deploy instructions

src/hint_deploy.py, test/test_integration.py
As discussed on slack, this will expose the hintr server to the network (practically this is on the VPN) so that we can implement the debug endpoint.
=> mrc-1308: Expose hintr port to the network

config/hint.yml, src/hint_deploy.py, test/test_integration.py
The actual commands for deploying are more complex than usual:
```
docker cp hint_redis:/data/dump.rdb .
docker volume create hint_redis_data
docker run --rm -v $PWD:/incoming -v hint_redis_data:/data alpine \
cp /incoming/dump.rdb /data/dump.rdb
docker run -d --rm --name redis_restore -v hint_redis_data:/data \
redis:latest
docker exec redis_restore redis-cli BGREWRITEAOF
docker logs -f redis_restore # wait here until write finishes
docker stop redis_restore
docker run -d --rm --name redis_restore -v hint_redis_data:/data \
redis:latest --appendonly yes
docker exec -it redis_restore redis-cli SMEMBERS hintr:worker:name
```
Then upgrade.
=> mrc-1316: persistent redis

config/production.yml, test/test_config.py
I think this was in unintentionally?
Noticed some errors in the logs on production which I am guessing is related to this
```
[http-nio-8080-exec-3] ERROR org.imperial.mrc.hint.logging.ErrorLoggingFilter - ERROR: 500 response for /adr/datasets/
[http-nio-8080-exec-3] ERROR org.imperial.mrc.hint.logging.ErrorLoggingFilter - {"data":{},"status":"failure","errors":[{"detail":"No response returned. The request may have timed out.","error":"OTHER_ERROR"}]}
```
=> Remove extra https:// from URL

src/hint_deploy.py, test/test_integration.py
This uses https://github.com/mrc-ide/hintr/pull/248
I've checked this in a local deploy by bringing up 1 "normal" worker and 1 calibrate worker and
* Trying to run 2 model runs and confirming the 2nd gets queued
* Running calibrate whilst a model is running and confirming it goes to calibrate worker
I guess we could also move this to a constellation service if we wanted to add multiple at some point. This is the sort of thing it would be cool to have monitoring on the worker to see how busy it is and whether there is value in adding more than 1.
=> Start a calibrate only worker during deploy

config/hint.yml, src/hint_deploy.py, test/test_integration.py
The issue we had here was the container was always called `hintr_worker_calibrate` and was not removed when doing `./hint upgrade hintr` so failed to restart as it would try to restart this container and clash with the name. It was also a bit confusing I think in the testing because of the similar names. So this PR will
* Use `hintr_calibrate_worker` for the name of calibrate workers to be more clear about difference and tidy up tests
* Make calibrate workers a ConstellationService which will give them a unique name and mean it can be restarted using `upgrade hintr`
* Explicitly restart this container when calling `upgrade hintr`
I mentioned in a message weirdness with the worker containers not getting removed. It looks like that is intended as the tests themselves check explicitly for …
=> Fix unable to restart calibration container on "upgrade hintr"

scripts/wait_for_redis, src/hint_deploy.py, test/test_integration.py
This PR will
* Add a script to test if redis can be used
Need this because we have seen on production redis taking a while to load persistent data and become useable. To the point hintr is starting and trying to connect before redis is ready resulting in failed deployments.
Not much testing here, hard to test the checking script itself but the impl is quite simple outside of that. There is a small test that the configure function gets run on container upgrade.
=> MRC-2112: Wait for redis to be useable before continuing deployment

config/production.yml
This PR will
* Change number of hint workers - this now matches what we have been using on production since the last workshop (I've just been lazy and not updated it in git)
* Adds a second calibrate worker - now we are running downloads async they are being run on the calibrate workers. I think we should make at least 2 of these available because the summary report can be slow generate
If I have time I will try make a kibana graph so we can see idle/busy time over next month and can think about adjusting worker number from that
=> Update number of workers

config/production_new.yml
This PR will
* Add config for naomi deployment on new server
This is currently deployed and can be checked at wpia-naomi.dide.ic.ac.uk
=> mrc-3362: Add naomi deployment on new server

backup/backup, backup/restore
This PR will add script to save snapshot of db, redis and uploaded files into tar archive and a script to then restore this state in on a new system. We need this because we want to move the production deployment onto the new server, but we could adapt it in future for storing a backup of the whole system state.
Note also we optionally save out a private a public key from the backup into the vault and then read this in in the restore. This is necessary because we store ADR keys encrypted and this is the keypair used to enable that encryption and decryption. If we want users to be able to use ADR keys entered on the old prod machine on the new prod machine then we need to migrate these over. This is done using the vault.
To test this
* ssh onto hint-dev and run `./backup/backup`
* ssh onto …
=> mrc-3367: Add backup and restore scripts

src/hint_deploy.py
We added this in #54 but forgot to put them into the config.properties
=> Add ADR URL and audience to config properties

scripts/fix_profile_encoding.groovy, scripts/run_fix_profile_encoding.sh
I'm not expecting this to be merged this is a 1 off script and I am just putting it here as a reference. I can move this to somewhere else if there is somewhere more appropriate.
We recently updated from pac4j 3.3.0 to 5.4.3 see https://github.com/mrc-ide/hint/pull/731/files
This update includes some changes to format for the serialised user profile in the database see https://github.com/pac4j/pac4j/blob/master/documentation/blog/what_s_new_in_pac4j_v5.md#b-serializedprofile
In particular 3.3.0 was using Java serialization and now pac4j uses JSON. This was resulting in errors on our end when trying to login as test.user on staging and preview (see ticket for errors). We wiped the volumes on dev deployment so the test.user there has serializedprofile in the new format. We can't just wipe …
=> mrc-3603: Migrate serializedprofile column to JSON serialization

backup/backup_remote, backup/restore_remote
This will add 2 shell scripts to create a backup and restore from a backup on a remote server
For review might be worth comparing to the standard `/backup/backup` and `/backup/restore` files
`git diff --no-index backup/backup backup/backup_remote`
`git diff --no-index backup/restore backup/restore_remote`
I have tested this by restoring dev using data written to wpia-naomi. From wpia-naomi-dev.dide.ic.ac.uk
```
git checkout mrc-3608
git pull
./backup/backup_remote vagrant@wpia-naomi.dide.ic.ac.uk:/home/vagrant/backup/
./hint stop --volumes --network
./backup/restore_remote vagrant@wpia-naomi.dide.ic.ac.uk:/home/vagrant/backup/2022_08_09-15_45_13.tar
./hint start dev
git checkout master
```
=> mrc-3608: Add backup and restore remote scripts

config/dev.yml, config/preview.yml, config/production.yml, config/production_new.yml, config/staging.yml, src/hint_deploy.py
This PR updates deployment config. Login method flag can be specified to use within 0Auth2 or not.
=> add login method to deployment config

config/dev.yml, config/preview.yml, config/staging.yml
After this PR we will have
* staging using standard/old login method (not OAuth)
* dev authentication with OAuth using our Auth0 instance (now called development)
* preview using the project balance/UNAIDS configured Auth0 instance (called production)
* production still using standard/old login
Note this removes the resource server config from preview as it looks like ADR won't get this in this year. The config here was incorrect anyway, we can always redeploy https://github.com/mrc-ide/hint-deploy/pull/53/files if someone wants to see the resource server working
=> Update paths to oauth secrets and use prod instance for preview naomi

.github/workflows/test.yml, .gitignore, README.md, requirements.txt, src/hint_deploy.py
This requies https://github.com/reside-ic/constellation/pull/16
Can test this by running
```
docker run  -l co.elastic.logs/json.add_error_key=true -it --rm --name naughty_rubin busybox echo '{"foo":"bar", "error_msg": "error opening file"}'
```
from a machine with filebeat running and see in the logs by searcing for `container.name: "naughty_rubin"`
it will unpack the JSON content of the log into fields called `json.key`. This option itself `add_error_key` you can see here https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-config-json it will add error info if the json fails to unpack. But having this set also triggers the autodiscover to unpack the json in the first place
=> Add labels to hintr container for controlling filebeat

config/preview.yml, config/production.yml, config/staging.yml
This doesn't turn on login with auth0 in production yet, once we get the go ahead after user migration is done we can switch `oauth2_login_method: true` in prod deploy and get this merged. After this we will have
* Dev and staging using auth0 but pointing to our development Auth0 tenant https://manage.auth0.com/dashboard/us/dev-xblynil1/
* Preview pointing to preview app in UNAIDS tenant (this will have same users as prod db, it is just a different app so we can test making configuration changes)
* Prod pointing to production app in UNAIDS tenant (atm disabled but all other config is in place)
=> Add auth0 configuration to prod

.gitignore, config/hint.yml, config/production.yml, src/hint_cli.py, src/hint_deploy.py, test/test_cli.py, test/test_integration.py
This is using https://github.com/mrc-ide/hintr-loadbalancer to loadbalance multiple hintr instances. At the moment this just brings up 1 hintr instance
This should mean hintr is less of a bottle neck in deployed applications. See https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3766/Investigate-system-load-issues for initial investigation
This is currently deployed on dev with 2 copies of hintr running, it is looking to be working nicely there!
Interesting parts of loadbalancer setup to review are 
* config - https://github.com/mrc-ide/hintr-loadbalancer/blob/main/haproxy.cfg
* backend configuration script - https://github.com/mrc-ide/hintr-loadbalancer/blob/main/bin/configure_backend
I will take a look now at using leastcon vs roundrobin
=> mrc-3838: Deploy load balancer as part of hint-deploy

scripts/fix_missing_serializedprofile.groovy, scripts/run_fix_missing_serializedprofile
Since switching to SSO when a new account is created we do not add a serializedprofile to the database. This is used when sharing a project with an email address. Meaning that if you try to share with a user without a serializedprofile then the app says that account does not exist. This PR has a migration script which fixes this for existing accounts by creating a serializedprofile for users where it is missing.
=> Add script to fix serialized profiles

config/dev.yml, config/staging.yml
This PR will update SSO config for dev and staging instances to work with SSO without needing an API key to pull data from the ADR
I've deployed this on dev and checked that is is working
=> Add SSO config for dev and staging

backup/backup, backup/backup_remote
When we last used this backup script there was only 1 instance of hintr running and I was using this with `volumes-from` flag. Now we have multiple hintrs I can't do this, so just updating to use `volumes-from` hint instead.
=> Update backup scripts to use hint container now running multiple hintr instances
